# Generated by Django 3.1.5 on 2021-01-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('credit_card', models.CharField(max_length=16)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('room_type', models.CharField(max_length=150)),
                ('beds', models.CharField(max_length=150)),
                ('accessible', models.BooleanField()),
                ('occupied', models.BooleanField()),
                ('spotless', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField(default='15:00:00')),
                ('check_out_date', models.DateField()),
                ('check_out_time', models.TimeField(default='12:00:00')),
                ('total_guests', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('rate', models.FloatField(default=100)),
                ('paid', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.guest')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.room')),
            ],
        ),
    ]
