# Generated by Django 3.1.5 on 2021-01-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.PositiveIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_date', models.DateField()),
                ('check_out_time', models.TimeField()),
                ('total_guests', models.PositiveIntegerField()),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=100)),
                ('guest_street', models.CharField(max_length=100)),
                ('guest_city', models.CharField(max_length=100)),
                ('guest_state', models.CharField(max_length=100)),
                ('guest_zip', models.CharField(max_length=100)),
                ('guest_country', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('paid', models.BooleanField()),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
