# Generated by Django 3.1.5 on 2021-01-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_street',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_zip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.room'),
        ),
    ]
