# Generated by Django 3.1.5 on 2021-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210121_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=150),
        ),
    ]
