# Generated by Django 3.1.5 on 2021-01-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210122_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmation',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default='15:00:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
