# Generated by Django 3.1.5 on 2021-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210122_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.FloatField(default=100),
        ),
    ]
