# Generated by Django 3.1.5 on 2021-01-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210125_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_guests',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
