# Generated by Django 3.1.5 on 2021-01-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210125_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='credit_card',
            field=models.CharField(default=1000200030004000, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='cvv',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='exp_month',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='exp_year',
            field=models.CharField(default=21, max_length=2),
            preserve_default=False,
        ),
    ]
